---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 80}]
    - ["forwarded_port", {guest: 443, host: 443}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-9.0

suites:
  - name: server
    run_list:
      - recipe[backuppc::nginx]
      - recipe[backuppc::server]
    attributes:
      backuppc:
        cgi:
          admin_pass: 'admin'
          certificate: '/etc/nginx/ssl/fake-cert.pem'
          certificate_key: '/etc/nginx/ssl/fake-key.pem'
