---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.4

suites:
  - name: default
    run_list:
      - recipe[aw-backuppc::default]
    attributes:
