---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: debian-9.0

suites:
  - name: default
    run_list:
      - recipe[aw_backuppc::nginx]
      - recipe[aw_backuppc::server]
    attributes:
      backuppc:
        cgi:
          admin_pass: 'admin'
