---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-9.0

suites:
  - name: server
    run_list:
      - recipe[backuppc::nginx]
      - recipe[backuppc::server]
    attributes:
      backuppc:
        cgi:
          admin_pass: 'admin'
